[package]
name = "jupiter_moons"
version = "0.1.0"
authors = ["Julien Philippon <julien.philippon@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.0"
regex = "1.3.1"
lazy_static = "1.4.0"
